### ISSUE TITLE
Dictionary key-value pair is removed from report if value = 0

### ISSUE THREAD

**Issue by hnrhonkala88** [OpenTMI/opentmi-pyclient#62]
### Description: Dictionary key-value pair is removed from report if value = 0
- Type: Bug

## Bug

**Severity:**
Minor

**opentmi-pyclient version**
v0.9.1

**python version**
3.7.9

**Expected Behavior**
If user puts key-value pair with value 0 to the report, key-value pair with value 0 exists

**Actual Behavior**
The key-value pair is removed from report

**Steps to Reproduce**
Add dictionary key-value pair, e.g. `result.execution.profiling['properties']["test_retries"] = 0` by using pytest-opentmi and verify the result.

**Comment by jupe** [comment]
fix coming here: https://github.com/OpenTMI/opentmi-pyclient/pull/63
